/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [3-1:0] M_dice8_out;
  reg [1-1:0] M_dice8_rollbtn;
  dice_2 dice8 (
    .clk(clk),
    .rst(rst),
    .rollbtn(M_dice8_rollbtn),
    .out(M_dice8_out)
  );
  
  wire [7-1:0] M_displayroll_segs;
  reg [3-1:0] M_displayroll_char;
  dice_seg_3 displayroll (
    .char(M_displayroll_char),
    .segs(M_displayroll_segs)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    M_dice8_rollbtn = 1'h0;
    M_dice8_rollbtn = io_button[0+0-:1];
    M_displayroll_char = M_dice8_out;
    io_seg = ~M_displayroll_segs;
    io_sel = 4'he;
  end
endmodule
