/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SEED = 128h843233523a613966423b622562592c62
*/
module randomnumber_9 (
    input clk,
    input rst,
    output reg out
  );
  
  localparam SEED = 128'h843233523a613966423b622562592c62;
  
  
  wire [1-1:0] M_edge_detector_rng_out;
  reg [1-1:0] M_edge_detector_rng_in;
  edge_detector_15 edge_detector_rng (
    .clk(clk),
    .in(M_edge_detector_rng_in),
    .out(M_edge_detector_rng_out)
  );
  reg [15:0] M_seed_d, M_seed_q = 1'h0;
  wire [1-1:0] M_clockk_value;
  counter_16 clockk (
    .clk(clk),
    .rst(rst),
    .value(M_clockk_value)
  );
  wire [32-1:0] M_random_number_num;
  reg [1-1:0] M_random_number_next;
  reg [32-1:0] M_random_number_seed;
  pn_gen_17 random_number (
    .clk(clk),
    .rst(rst),
    .next(M_random_number_next),
    .seed(M_random_number_seed),
    .num(M_random_number_num)
  );
  
  reg [2:0] temp_pointer;
  
  always @* begin
    M_seed_d = M_seed_q;
    
    out = 1'h0;
    M_random_number_seed = M_seed_q;
    M_edge_detector_rng_in = M_clockk_value;
    M_random_number_next = M_edge_detector_rng_out;
    temp_pointer = M_random_number_num[0+2-:3];
    if (M_edge_detector_rng_out) begin
      M_seed_d = M_seed_q + 1'h1;
    end
    
    case (temp_pointer)
      1'h0: begin
        out = M_seed_q[0+0-:1];
      end
      1'h1: begin
        out = M_seed_q[1+0-:1];
      end
      2'h2: begin
        out = M_seed_q[2+0-:1];
      end
      2'h3: begin
        out = M_seed_q[3+0-:1];
      end
      3'h4: begin
        out = M_seed_q[4+0-:1];
      end
      3'h5: begin
        out = M_seed_q[5+0-:1];
        out = 1'h0;
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_seed_q <= M_seed_d;
  end
  
endmodule
