/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [8-1:0] M_eightbitSL_s;
  reg [8-1:0] M_eightbitSL_a;
  reg [3-1:0] M_eightbitSL_b;
  eight_bit_shiftleft_1 eightbitSL (
    .a(M_eightbitSL_a),
    .b(M_eightbitSL_b),
    .s(M_eightbitSL_s)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_eightbitSL_a = io_dip[0+7-:8];
    M_eightbitSL_b = io_dip[8+0+2-:3];
    io_led[0+7-:8] = M_eightbitSL_s;
  end
endmodule
