/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module eight_bit_shiftleft_1 (
    input [7:0] a,
    input [2:0] b,
    output reg [7:0] s
  );
  
  
  
  reg [7:0] w;
  
  reg [7:0] x;
  
  always @* begin
    
    case (b[2+0-:1])
      1'h0: begin
        w = a;
      end
      1'h1: begin
        w[0+3-:4] = 4'h0;
        w[4+3-:4] = a[0+3-:4];
      end
      default: begin
        w = a;
      end
    endcase
    
    case (b[1+0-:1])
      1'h0: begin
        x = w;
      end
      1'h1: begin
        x[0+1-:2] = 2'h0;
        x[2+5-:6] = w[0+5-:6];
      end
      default: begin
        x = w;
      end
    endcase
    
    case (b[0+0-:1])
      1'h0: begin
        s = x;
      end
      1'h1: begin
        s[0+0-:1] = 1'h0;
        s[1+6-:7] = x[0+6-:7];
      end
      default: begin
        s = x;
      end
    endcase
  end
endmodule
