/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module full_adder_ROM_1 (
    input [2:0] address,
    output reg [1:0] value
  );
  
  
  
  localparam FULL_ADDER = 16'hd668;
  
  always @* begin
    value = FULL_ADDER[(address)*2+1-:2];
  end
endmodule
